language: java
jdk:
  - oraclejdk8
dist: trusty
sudo: required
script:
  - ./gradlew -P esVersion=5.4.0 -P projectVersion=$TRAVIS_TAG build
  - ./gradlew wrapper --gradle-version 2.13 --distribution-type all
  - ./gradlew -P esVersion=5.3.2 -P projectVersion=$TRAVIS_TAG build
  - ./gradlew -P esVersion=5.3.1 -P projectVersion=$TRAVIS_TAG build
  - ./gradlew -P esVersion=5.3.0 -P projectVersion=$TRAVIS_TAG build
