language: java
jdk:
  - oraclejdk8
dist: trusty
sudo: required
script:
  - gradle wrapper --gradle-version 3.5 --distribution-type all
  - ./gradlew -P esVersion=5.4.0 build
  - gradle wrapper --gradle-version 2.13 --distribution-type all
  - ./gradlew -P esVersion=5.3.2 build
  - ./gradlew -P esVersion=5.3.1 build
  - ./gradlew -P esVersion=5.3.0 build
