language: java
services:
  - docker

dist: trusty
sudo: false
stages:
  - build
  - build-console
  - name: docker
    if: tag IS present

jobs:
  include:
    - stage: build
      jdk: oraclejdk9
      env:
        - ES=6.2.1
        - GRADLE=4.5.1
      script: &script
      - ./gradlew wrapper --gradle-version $GRADLE -PskipEsPlugin
      - ./gradlew -P esVersion=$ES -P projectVersion=$TRAVIS_TAG build
    - stage: build
      jdk: oraclejdk9
      env:
        - ES=6.2.0
        - GRADLE=4.5.1
      script: *script
    - stage: build
      jdk: oraclejdk8
      env:
        - ES=6.1.3
        - GRADLE=4.5.1
      script: *script
    - stage: build
      jdk: oraclejdk8
      env:
        - ES=6.1.2
        - GRADLE=4.5.1
      script: *script
    - stage: build
      jdk: oraclejdk8
      env:
        - ES=6.1.1
        - GRADLE=4.5.1
      script: *script
    - stage: build
      jdk: oraclejdk8
      env:
        - ES=6.1.0
        - GRADLE=4.5.1
      script: *script
    - stage: build
      jdk: oraclejdk8
      env:
        - ES=6.0.1
        - GRADLE=4.0.2
      script: *script
    - stage: build
      jdk: oraclejdk8
      env:
        - ES=6.0.0
        - GRADLE=4.0.2
      script: *script
    - stage: build
      jdk: oraclejdk8
      env:
        - ES=5.6.7
        - GRADLE=4.5.1
      script: *script
    - stage: build
      jdk: oraclejdk8
      env:
        - ES=5.6.6
        - GRADLE=4.5.1
      script: *script
    - stage: build
      jdk: oraclejdk8
      env:
        - ES=5.6.5
        - GRADLE=4.0.2
      script: *script
    - stage: build
      jdk: oraclejdk8
      env:
        - ES=5.6.4
        - GRADLE=4.0.2
      script: *script
    - stage: build
      jdk: oraclejdk8
      env:
        - ES=5.6.3
        - GRADLE=4.0.2
      script: *script
    - stage: build
      jdk: oraclejdk8
      env:
        - ES=5.6.2
        - GRADLE=4.0.2
      script: *script
    - stage: build
      jdk: oraclejdk8
      env:
        - ES=5.6.1
        - GRADLE=4.0.2
      script: *script
    - stage: build
      jdk: oraclejdk8
      env:
        - ES=5.6.0
        - GRADLE=4.0.2
      script: *script
    - stage: build
      jdk: oraclejdk8
      env:
        - ES=5.5.3
        - GRADLE=4.0.2
      script: *script
    - stage: build
      jdk: oraclejdk8
      env:
        - ES=5.5.2
        - GRADLE=4.0.2
      script: *script
    - stage: build
      jdk: oraclejdk8
      env:
        - ES=5.5.1
        - GRADLE=4.0.2
      script: *script
    - stage: build
      jdk: oraclejdk8
      env:
        - ES=5.5.0
        - GRADLE=4.0.2
      script: *script
    - stage: build
      jdk: oraclejdk8
      env:
        - ES=5.4.3
        - GRADLE=4.0.2
      script: *script
    - stage: build
      jdk: oraclejdk8
      env:
        - ES=5.4.2
        - GRADLE=4.0.2
      script: *script
    - stage: build
      jdk: oraclejdk8
      env:
        - ES=5.4.1
        - GRADLE=4.0.2
      script: *script
    - stage: build
      jdk: oraclejdk8
      env:
        - ES=5.4.0
        - GRADLE=4.0.2
      script: *script
    - stage: docker
      env:
        - PROMETHEUS=v2.1.0
      script: &promscript
        - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
        - cp elastic-rules.rule.yml prometheus/elastic-rules.yml
        - "docker build --build-arg PROMETHEUS=$PROMETHEUS -t jsuchenia/prometheus-elasticsearch:$PROMETHEUS-$TRAVIS_TAG prometheus"
        - docker push jsuchenia/prometheus-elasticsearch:$PROMETHEUS-$TRAVIS_TAG
    - stage: docker
      env:
        - PROMETHEUS=v2.0.0
      script: *promscript

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

install: true

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

deploy:
  provider: releases
  api_key:
    secure: X9SnIX47G9hhl8+oVg17vfZFkE2TG/FVG7PU1oy2NPejPy+JfFeTNPZbJE08CZtjO99+IjZCHDObxTCwe5Q1VxgYB+bZADwhlm7n9rHjb6vNL4TICSq9IRYCcl0FQ63WkAXdAjGqFqmz7vhKT+cC5p73xoxVrSPZiiwOh26HZp7O7sicJFUBTo9IzTqvOsAFCnsqNVhRuVzFR2J3Z3bLIP3llu1O+I5hbLdn4uyOy4YcetH/MTH/HxsObMv0Oa7UOc7S1mzO6aAam134B3FPAPh0F9r3yjSbmloEob//WsoD0Q1RXqvt0DxpTUruKWTKDOysO+CNhg9mTjBfSGvdcPfz4Y2FxNlGBp69GWn6gF6TKUa5G0exCs6gUiWYdF7TP0gXx1aSm3MqFEP8yDmK8QS3nROpOvq+1VkqIdewcVnvC2Dkl/Ot7QLFuPrxWdFgr3HSQnUZr7fVbPiPxsIMhw35/Bnhy/JZYfsVkJwBQX0FkIGvXSADrDJZC1kAJhlAAjUoxL1eR6s6VdX31geKizV3bN5VK+w/4xIVFtxFEMoU3iupkh2C7ZhS7d8Ym2VHhVQnWn4b/Zw/ZG08MoLJ31zLzJjbxLjOGN8cGYzlKVr7yIX7qC7xc5nNxTr2Jm6MUk6eQTZZ7AwcFxD+JrcpcVmLrR/r0Ikc5Xf90arPkEI=
  file_glob: true
  file:
  - build/distributions/*.zip
  - elastic-rules.*
  skip_cleanup: true
  on:
    tags: true
    repo: jsuchenia/elasticsearch-prometheus-metrics
